### ISSUE TITLE
Deciding on a path forward.

### ISSUE THREAD

**Issue by 1point618** [wheelhouseio/curriculum-patchwork#1]
Hi @ElizabethN! Below are my thoughts on what we could start working on in January. Let me know what you think :smile: 
# Patchwork and Wheelhouse
## Goals
1. To build 3-4 modules for Patchwork to use in their events.
2. Modules can be new material, or remixing old material.
3. At least one intro to GitHub module.
4. Modules should be built to let students work through on their own, with the assumption that they can ask for help from mentors when the get stuck.
## Options

Below I outline 5 modules in detail:
1. The GitHub Workflow
2. OSS and Forking
3. Intro to Git on the Command Line
4. Intermediate Git
5. Getting Started with GitHub Pages

We need to pick which modules we'll focus on working on for this first contract.
- We get (1) "for free" since re-working the content from our demo module is trivial.
- (2), (3), and (4) will all take a similar amount of work for us to build.
- (5) is a much larger undertaking.

As such, I see several potential packages that we might decide upon.
- (1), (2), (3), and (4) — A focus on building as many modules as we can. 
- (1), (2), and (5) — A focus on GitHub modules.
- (1), (3), and (5) — A focus on the intro modules.
- (1), (4), and (5) — A focus on the intermediate modules.

Before we can move on, we need to hear from Patchwork which of these packages they'd want to build. 
### The GitHub Workflow
- Purely GH-based module.
- Walk the student through branching, committing, submitting a PR, commenting, editing, and merging the PR.
#### Benefits
- We already have this content, will be trivial to remix it for Patchwork.
- Many students need this intro.
#### Cons
- None?

---
### OSS and Forking
- Purely GH-based module.
- Focus on the GH workflow, but from Forks, not Branches.
- Include information on using Issues to communicate.
- Include some information on working with OSS projects.
#### Benefits
- Content is easy to build on top of content we already have.
- It's an interest of Patchwork and some students.
#### Cons
- Applying webhooks to forked repos might be difficult.
- Is it too close in content to the GH WF module?

---
### Intro to Git on the Command Line
- Command line focused module.
- Do the things you'd normally do on GH, but locally.
- Focus on GH Workflow and not much more.
- Include information on getting the machine set up: text editor, git, other command line tools.
#### Benefits
- We already have a lot of this content and could easily re-mix it for Patchwork.
- Difficult content would work well with the mentor there.
#### Cons
- Cannot do many online validations.
- Students will have many different kinds of machines to work on.
- Getting local software working can be tricky.

---
### Intermediate Git
- Going beyond the Workflow to talk about Git's more advanced features, such as resetting, having multiple remotes, merging/pushing/pulling, etc.. 
- Would have to do more research on what exactly to include.
#### Benefits
- Same as above.
#### Cons
- Same as above.
- In addition, how many students would this really help?

---
### Getting Started with GitHub Pages
- An intro to how to use GitHub Pages
- Jekyll | Markdown ?
- The gh-pages branch and some advanced branching features
- No HTML/CSS, students must know that before hand
#### Benefits
- Students get the instant feedback of seeing their project online.
- We can build a class repo that begins the project for the student.
- It's interesting content that other parts of GH also want to see.
- We can validate a good portion of the work.
#### Cons
- This will take longer for students to do.
- There is some command-line stuff they'll have to do, maybe hard for less advanced students.
- Teaching HTML/CSS is outside of our scope.

**Comment by ElizabethN** [comment]
:wave: @1point618 thanks for putting this all in an issue! This is perfect! 

> (1), (3), and (5) — A focus on the intro modules.

I think this option is best, given Patchwork's target market of beginners to Git, GitHub and open source.

That being said, modules 2 and 4 are also desirable, so maybe we could include them in a Phase II for Q2 or end of Q1?

I am completely fine with the content as you've outlined for the modules. :+1:

One point of clarification, how does this plan coincide with the originally quoted fee? Would the fee be for the first 3 modules only?

Thanks again for putting this together! :+1: It looks wonderful.

**Comment by 1point618** [comment]
@ElizabethN Sounds great! So just to confirm, in January I'll be working on the following modules for you:
1. The GitHub Workflow
2. Intro to Git on the Command Line
3. GitHub Pages

If you'd like a sneak peek at the demo I'll be basing The GitHub Workflow on, that's [here](https://github.wheelhouse.io/events/OfmkjpnIcuLDhIYhD87J). The content for Git on the Command line will come from sections 5, 6, and 7 from our [GitHub for Devs course](https://learn.wheelhouse.io/events/early-access/), and will see extensive revision. The GitHub Pages content will all be brand new!

I will likely focus on getting (1) and (2) out the door as quickly as possible, and (3) will take a bit longer. I can do the work of cleaning up (1) and (2) for Patchwork while Peter writes the content for (3), which I'll then do the work of building a project for. 

---

The fee only covers this first stage of work, but doing more in late Q1/early Q2 shouldn't be an issue. I'm happy to discuss the details of that whenever you want to. Let's maybe start on the current project so we have some sense of how the work actually goes before getting too far in the weeds on planning the next project?

**Comment by ElizabethN** [comment]
> So just to confirm, in January I'll be working on the following modules for you:

```
The GitHub Workflow
Intro to Git on the Command Line
GitHub Pages
```

:+1: sounds great! 

> Let's maybe start on the current project so we have some sense of how the work actually goes before getting too far in the weeds on planning the next project?

:+1: sounds great here, too! 

Thanks so much!

**Comment by 1point618** [comment]
Excellent :fireworks: :sparkles: !

You might see me updating this repo before the new year, but most likely I'll really get started in earnest come January.
